version: '3.9'

services:

  mcp:
    build: ./dpa-review-mcp
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - graphrag
      - agent
      - knowledge-base
    environment:
      MCP_PORT: ${MCP_PORT}
      KB_PORT: ${KB_PORT}
      GRAPHRAG_PORT: ${GRAPHRAG_PORT}
      AGENT_PORT: ${AGENT_PORT}


  knowledge-base:
    build: ./ln-dpo-node-app
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    volumes:
      - /app/docs:/app/docs      
    environment:
      MONGODB_USERNAME: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DB: ${MONGODB_DB}
      MONGODB_URL: ${MONGODB_URL}
      PORT: ${KB_PORT}   
      DOCUMENT_FOLDER_PATH: ${DOCUMENT_FOLDER_PATH}

  graphrag:
    build: ./document-graph-provider
    ports:
      - "3002:3002"
    volumes:
      - /app/docs:/app/docs
    environment:
      PORT: ${GRAPHRAG_PORT}
      NEO4J_URI: ${NEO4J_URI}
      NEO4J_USERNAME: ${NEO4J_USERNAME}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      NEO4J_DATABASE: ${NEO4J_DATABASE}
      MS_GRAPHRAG_ROOT: ${DOCUMENT_FOLDER_PATH}/ms_graphrag
      OPENAI_API_KEY: ${OPENAI_API_KEY}


  agent:
    build: ./LegalNodesRAISE
    ports:
      - "8002:8002"

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - /app/mongo:/data/db
    ports:
      - 27000:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
